services:

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres/data

  redis:
    image: redis
    volumes:
      - redis_data:/data

  js:
    build:
      context: "."
    command: "yarn build --watch"
    volumes:
      - .:/usr/src/your_application

  css:
    build:
      context: "."
    command: "yarn build:css --watch"
    volumes:
      - .:/usr/src/your_application

  web:
    build: .
    entrypoint: ./entrypoint-dev.sh
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/usr/src/your_application
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - RAILS_MAX_THREADS=5
      - RAILS_ENV=development
      - RACK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
      - redis
      - js
      - css

volumes:
  postgres_data:
  redis_data:
  bundle:
